- hosts: cloudkey
  remote_user: root
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
  roles:
    - bootstrap
    - ssh_hardening

- hosts: cloudkey
  remote_user: root
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh_keys/root_ed25519"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - storage
    - users
    - chezmoi