---
- name: 1️⃣ Bootstrap with password (if needed)
  hosts: cloudkey
  remote_user: root
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_pass: "{{ lookup('env','ANSIBLE_PASSWORD') }}"
  pre_tasks:
    - name: “Check if key-auth already works”
      ping:
      vars:
        # override to test key auth only
        ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh_keys/root_ed25519"
      register: key_auth
      ignore_errors: yes

    - name: “Skip bootstrap if key is already installed”
      meta: end_play
      when: key_auth is succeeded

  roles:
    - bootstrap
    - ssh_hardening

- name: 2️⃣ Harden & daily operations (key login)
  hosts: cloudkey
  remote_user: root
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh_keys/root_ed25519"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - system
    - storage
    - users
    - chezmoi
