- hosts: cloudkey
  remote_user: root
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
  roles:
    - bootstrap

- hosts: cloudkey
  remote_user: root
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: playbooks/files/root_id_ed25519
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - ssh_hardening
    - storage
    - users
    - upgrade
    - chezmoi